### ISSUE TITLE
how to start the SemanticMediaWiki?

### ISSUE THREAD

**Issue by yejiyang** [toniher/docker-SemanticMediaWiki#2]
I can run `smw.sh` successfully, and get two docker images (smw and mariadb:10.1) running. When I type http://0.0.0.0:10080/ in the web browser, I get "403 Forbidden".  

What's the correct way to start the smw site after the installation? 
Many thanks!

**Comment by yejiyang** [comment]
I figure out http://localhost:10080/wiki/  is the correct way to start.

**Comment by csik** [comment]
I get an NGINX bad gateway notice at this address:
http://localhost:10080/wiki/

All four containers appear to be running fine...
